version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: tracker-bot
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - BOT_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
